[package]
name = "simbuf"
version = "0.1.0"
edition = "2021"

[dependencies]
codec = { version = "3.6", package = "parity-scale-codec", optional = true }

[features]
default = ["std"]
std = ["codec?/std"]
parity-scale-codec = ["dep:codec"]
